# Languages
#   Create a section for each of your site's languages.
#   Documentation: https://wowchemy.com/docs/guide/language/


# Uncomment the lines below to configure your website in a second language.
ja:
 languageCode: ja
 contentDir: content/jp
 languageName: "日本語"
 #disabled: false
 title: 岐阜大学 工学部 情報コース 盧研究室
 params:
   description: 岐阜大学 工学部 情報コース 盧研究室のホームページです．


# Default language
en:
  languageCode: en-us
  # Uncomment for multi-lingual sites, and move English content into `en` sub-folder.
  contentDir: content/en

# Uncomment the lines below to configure your website in a second language.
zh:
 languageCode: zh-Hans
 contentDir: content/zh
 title: Chinese website title...
 params:
   description: Site description in Chinese...
#  menu:
#    main:
#      - name: 传
#        url: '#about'
#        weight: 1
